#CORES
WHITE = [255, 255, 255]
RED = [255, 0, 0]
BROWN_SKY = [249, 203, 133]
BROWN_SAND = [230, 129, 58]

# TAMANHO DA TELA / ESSE SERÁ O PADRAO
WIDTH = 800
HEIGHT = 400

#DIVISAO QUE O BURACO DA BOLA VAI FICAR
#TIPO ASSIM: O BURACO DA BOLA VAI
#FICAR NA DIVISÃO x_div - 1, OU SEJA,
#SE O VALOR FOR 0, O BURACO VAI FICAR 
#DIVISÃO DE NÚMERO x_div - 0, OU SEJA,
#A ÚLTIMA DIVISÃO NO X. SE O VALOR FOR 1,
#FICAR NA PENULTIMA E ASSIM VAI.
#ESSE VALOR NUNCA DEVE SER MAIOR QUE x_div.
#HOLE_DIV <= x_div
HOLE_DIV = 2